name: initialize-status-checks
on:
  workflow_dispatch:

jobs:
  init-checks:
    runs-on: ubuntu-latest
    name: "Run initialization checks"
    steps:
      - name: Setup minimal
        run: echo "Initializing checks"

      - name: "ğŸ§¹ Format"
        run: echo "Format initialization"
        continue-on-error: true
        id: format

      - name: "ğŸ” Lint"
        run: echo "Lint initialization"
        continue-on-error: true
        id: lint

      - name: "ğŸ§  Typecheck"
        run: echo "Typecheck initialization"
        continue-on-error: true
        id: typecheck

      - name: "ğŸ› ï¸ Build"
        run: echo "Build initialization"
        continue-on-error: true
        id: build